import = [
#	"~/.config/alacritty/colors/cloud.toml",
#	"~/.config/alacritty/colors/iterm.toml",
	"~/.config/alacritty/colors/monochrome.toml",
]

[font]
size = 7
normal = { family = "monospace", style = "Normal" }

[window]
opacity = 0.8

# [cursor]
# style = { shape = "underline" }

[shell]
program = "/bin/zsh"

[colors.cursor]
cursor = "#55FF55"
text = "#000000"

[colors.primary]
background = "#000000"

