# Colors (iTerm 2 default theme)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#C5C8C6'
red     = '#C5C8C6'
green   = '#C5C8C6'
yellow  = '#C5C8C6'
blue    = '#C5C8C6'
magenta = '#C5C8C6'
cyan    = '#C5C8C6'
white   = '#C5C8C6'

# Bright colors
[colors.bright]
black   = '#ffffff'
red     = '#ffffff'
green   = '#ffffff'
yellow  = '#ffffff'
blue    = '#ffffff'
magenta = '#ffffff'
cyan    = '#ffffff'
white   = '#ffffff'
